### PR TITLE
Enhance kfserving integration

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:
Enhance kfserving integration, move to new version of kfserving, and the CRD has been changed to Inferenceservice, updated in Fairing accordingly.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/407)

### CODE REVIEW

**Comment by jinchihe** [comment]
May be better to use kfserving SDK for integration. I'm going to take a look. Thanks.

**Comment by jinchihe** [comment]
/cc @abhi-g @ellis-bigelow @yuzisun @animeshsingh 

That's ready for reviewing, could you please take a look for the integration? Thanks a lot!

**Comment by abhi-g** [comment]
Thanks @jinchihe 
/lgtm
/approve

**Comment by abhi-g** [comment]
@jinchihe looks like there is some issue with xgboost high level API
notebook deploying the model in final step. I'll look into it.

**Comment by abhi-g** [comment]
@jinchihe can you please merge upstream/master to pull in test fixes

**Pull request merged**
