### PR TITLE
Remove travis config file

### PR DESCRIPTION
**Pull request by rpasricha**
Also testing that cloud builds get triggered in the repo

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/94)

### CODE REVIEW

**Comment by karthikv2k** [comment]
Let's merge once we see the cloud build integration is working.

**Comment by abhi-g** [comment]
We were trying to test the integration by merging this PR :) 
For now the cloud build integration works as a Post Submit. We'll need to figure out how to get it working with PR pre-submit

**Comment by karthikv2k** [comment]
Let's have travis for doing pre-submit tests. It may not be all but it is better than none.

**Pull request closed without merging**
