### PR TITLE
Support specifying GPU resource

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jinchihe** [comment]
/assign @abhi-g 
Would you please take a look? Thanks!

**Comment by fenglixa** [comment]
Thanks @jinchihe 
/lgtm

**Comment by velascoluis** [comment]
Hi @jinchihe , any way to make this work with a managed backend? (eg. Run train job on GCP with GPU)

**Pull request merged**
