### PR TITLE
Make fairing as a subpackage in kubeflow

### LINKED ISSUE #234: Figure out python packaging for fairing
I think fairing is imported as 

```
import fairing
```

Should we instead make this a subpackage in "kubeflow"

e.g.

```
import kubeflow.fairing
```

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:

Make fairing as a subpackage in kubeflow, see more in #234

After the PR, fairing will be a subpackage in kubeflow. and the changes are as following:
1. Created new kubeflow foler, and moved fairing and containerregistry to kubeflow. 
2. Updated some imports to `from kubeflow import fairing` and `import kubeflow.fairing`.

For the kubeflow python sdk, user can install by 
```
pip install kubeflow-fairing
```

**Which issue(s) this PR fixes**:
Fixes #234

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Fairing is a subpackage in `kubeflow`.
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/359)

### CODE REVIEW

**Comment by jinchihe** [comment]
Hello @jlewi @abhi-g @karthikv2k , the PR is ready for reviewing, thanks a lot!

**Comment by jinchihe** [comment]
/assign @jlewi 
/assign @abhi-g 

Could you please help to review? Thanks a lot!

**Comment by jlewi** [comment]
Would a user really do pip install kubeflow? Or does it depend on how we upload this to the pip repository?

**Comment by jlewi** [comment]
One minor comment on my end; it looks like setup.py is naming the package to "kubeflow" per my comments in #234 I prefer to keep the pip package named such that it reflects the fact that fairing is just one subpackage. 

Could we change it to something like 

```
pip install kubeflow-fairing
```

**Comment by jinchihe** [comment]
Hello @jlewi @abhi-g 

Addressed your comments, updated the PR using [pkgutil-style namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/#pkgutil-style-namespace-packages) which supports Python 2. See more discussion with @jlewi in https://github.com/kubeflow/fairing/issues/234  For now the Fairing is kubefloe subpacakge, and user can install kubeflow-fairing by:
```
pip install kubeflow-fairing
```

Ready for checking in,  please view. thanks!

**Comment by jlewi** [comment]
Whoo Hooo!
/lgtm
/approve
/hold 

@jinchihe Can you open issues to update the examples and docs? They should probably be P0 and filed under project 0.7.

I think we should probably get the xgboost_synthetic example updated at a minimum.

You can remove the hold. I just wanted you to see this comment and file the issues. Thanks

**Comment by jinchihe** [comment]
@jlewi Yes, already logged ticket in examples https://github.com/kubeflow/examples/issues/636 and doc https://github.com/kubeflow/website/issues/1146, and assigned to me, will update very soon.

/hold cancel

**Pull request merged**
