### PR TITLE
Generate docs for fairing APIs

### LINKED ISSUE #326: Add document for Fairing APIs
/kind feature

**Describe the solution you'd like**
Kubeflow Fairing should have baisc documents for Fairing APIs, so that the user can just reading the documents when calling APIs, instead of reading code.

**Anything else you would like to add:**

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:
Generate the Docs for Fairing APIs.

I prefer to use the sphinx to generate the docs for Fairing APIs. I would like have a demo for the Fairing community to show my thoughts by the PR.

I created the script `doc-gen.sh`, maintainer just need to execute the script to generate new docs after add new functions/features or updated the docstrings for some functions/classes, and then create PR to merge that.

**Note**:  Creating the PR is to show my proposal for generating docs for Fairing APIs, and will discuss with Fairing community, if have better solution, the ticket will be closed. Thanks

**Which issue(s) this PR fixes** :
Fixes #326 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/338)

### CODE REVIEW

**Comment by jinchihe** [comment]
@karthikv2k As shown in the meeting just now, what do you think for this? If you also agree that's good choose using `sphinx`, so check in the `doc-gen.sh` and immature docs?  If so, someone updated the docStrings for the APIs laster, just ran the script to generate docs diff and can check the result directly, and fixing the warning or error if any during generating.

**Comment by jinchihe** [comment]
I geneated two types doc: html and markdown, since we cannot review the html page directly unless set up html server or using the tools such as https://htmlpreview.github.io/, so I genereated markdown type so user can read that directly, seems for user experience, seems html is better than markdown. So just generated two types. Thanks.

**Comment by jinchihe** [comment]
@sarahmaddox We are going to generate the Fairing documents, I'm wonder is that possiable to put the html docs in our `kubeflow.org`? can we create a link(Fairing) on top right corner of the `kubeflow.org` to link to faring html page? Thanks.

**Comment by sarahmaddox** [comment]
> @sarahmaddox We are going to generate the Fairing documents, I'm wonder is that possiable to put the html docs in our `kubeflow.org`? can we create a link(Fairing) on top right corner of the `kubeflow.org` to link to faring html page? Thanks.

Hallo @jinchihe Thanks for generating these docs! You should create a new **Reference** section in the Fairing section of the docs:
https://www.kubeflow.org/docs/fairing/

To do that, follow the pattern of the "Reference" section in the Pipelines section of the docs:
https://www.kubeflow.org/docs/pipelines/

When ready, please send your PR to @joeliedtke for review. He can help you with getting the doc metadata and structure correct.

**Comment by sarahmaddox** [comment]
Hallo Abhishek, I'm on a plane, so this response will be delayed. The ref
docs should be on kubeflow.org. I added a comment earlier in this thread
with some info.

**Comment by jinchihe** [comment]
Agree, I generated two types docs: html and markdown. The html docs are great for end users. please see below attachment for my quick demo pictures. We may need put those html docs to html server. for markdown, that's ok both for github repo and `kubeflow.org`.

@sarahmaddox I'm not sure if we can put the html docs to `kubeflow.org` (working as html server side).

/cc @jlewi 

图片
图片
图片

**Pull request merged**
