### PR TITLE
add jinchihe to owners

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:

Add me to OWNERS, as I'm very interested in faring, and tested some cases for on-prem cluster, and fix some bugs, contributing features such as supporting kfserving and pylint checking (almost done). Will continue contributing and maintaining the project from IBM side. Thanks.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/303)

### CODE REVIEW

**Comment by karthikv2k** [comment]
Thanks @jinchihe for all your contributions! These are great for the community. 
Typically we add the contributors as reviewers first and then based on their continued contribution, promote them to approvers and then to owners.

Can we start with adding you as a reviewer first?

**Comment by jinchihe** [comment]
@karthikv2k OK, updated. Thanks :)

**Comment by karthikv2k** [comment]
Thanks again for your contributions.

/lgtm
/approve

**Comment by jinchihe** [comment]
> Thanks again for your contributions.
> 
Thank you! I am very honored to do this, :-)

**Pull request merged**
