### PR TITLE
Adding more optional parameters

### PR DESCRIPTION
**Pull request by hamedhsn**
Provide a capability to pass a few options when running job
- job_name
- image_pull_policy
- restart_policy

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/52)

### CODE REVIEW

**Comment by wbuchwalter** [comment]
Do we really want this to be controlled at the user level?
Fairing shouldn't expose all possible parameters that are available on the pod/job spec.
Could this be just solved by sane default in the builder?
If there is really a need for customization, could this be solved with the admin config (https://github.com/kubeflow/fairing/issues/28) instead?

**Comment by hamedhsn** [comment]
hmm.. I see.
configmap make sense for really admin stuff like image_pull_policy or restart policy, however, users might want to pick the name for their jobs. This will make it easier once multiple users submit different jobs. Based on my observation, in most of the case names are chosen meaningful to the experiments.
Any further operations make it easier once it has a custom name.

**Comment by hamedhsn** [comment]
closing this as it is old and was before major refactoring.

**Pull request closed without merging**
