### PR TITLE
Implement AWSBackend and S3Context

### LINKED ISSUE #282: Support AWS environment
/kind feature

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
* Support S3 as context resource.
* Support Kubernetes in AWS as Backend.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by takmatsu**
This patch enables kubeflow-fairing to run in AWS environment(EKS, S3, ECR...) like this.

```
import os
import fairing

DOCKER_REGISTRY = '{account_id}.dkr.ecr.{region}.amazonaws.com'
PY_VERSION = ".".join([str(x) for x in sys.version_info[0:3]])
BASE_IMAGE = 'python:{}'.format(PY_VERSION)
```
```
from fairing import TrainJob
from fairing.backends import KubeflowAWSBackend
train_job = TrainJob(HousingServe, BASE_IMAGE, input_files=['ames_dataset/train.csv', "requirements.txt"],
                     docker_registry=DOCKER_REGISTRY, backend=KubeflowAWSBackend())
train_job.submit()
```

Fixes #282 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/263)

### CODE REVIEW

**Comment by netankit** [comment]
@takmatsu  How does one supply their own aws credentials. Would be nice to add in an example. Something on the same lines as pipelines example like this can help standardize this:

```
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: kubeflow
type: Opaque
data:
  AWS_ACCESS_KEY_ID: YOUR_BASE64_ACCESS_KEY
  AWS_SECRET_ACCESS_KEY: YOUR_BASE64_SECRET_ACCESS
```
Link: https://github.com/kubeflow/pipelines/tree/master/samples/aws-samples/mnist-kmeans-sagemaker

**Comment by takmatsu** [comment]
@netankit Thank you for your feedback. I changed the credential implementation from credentials file to aws-secret.

**Comment by netankit** [comment]
@takmatsu  Thanks for the update. In addition, regarding the default kubeflow bucket and ECR repo, one should specify these in their code. In my case, I didn't have access to create new s3 buckets or know which ECR repo is required to be created and in both cases i got halted. One should be able to pass them as constants or parameters.

**Comment by karthikv2k** [comment]
@takmatsu can you address @netankit 's asks? Also can you rebase your PR? Thanks. I will have some time this week to get this merged.

**Comment by takmatsu** [comment]
> bucket

It should be specified in context parameter, i will implement after #281 is merged.

> ECR repo

This problem is essentially we have no way to specify image_name in backend (`fairing-job` is fixed)
I think new issue will be fine.

**Comment by takmatsu** [comment]
rebased. can you check me again? @karthikv2k

**Comment by karthikv2k** [comment]
Thanks.

/lgtm
/approve

**Pull request merged**
