### PR TITLE
Support configuring environment variables

### LINKED ISSUE #492: Fairing Serving job user can not set the custom environment vars
/kind feature

**Describe the solution you'd like**
so far, for the Faring Serving Job , user can not set the specific custom environment vars like the custom command, is it possible let user to set the env parmameters like command in the preprocessor to build in the pod spec?

_[class BasePreProcessor(object)](https://github.com/kubeflow/fairing/blob/master/kubeflow/fairing/preprocessors/base.py):
    """Prepares a context that gets sent to the builder for the docker build and sets the entrypoint
    :param input_files: the source files to be processed
    :param executable: the file to execute using command (e.g. main.py)
    :param output_map: a dict of files to be added without preprocessing
    :param path_prefix: the prefix of the path where the files will be added in the container
    :param command: the command to pass to the builder_

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:
Support configuring environment variables
**Which issue(s) this PR fixes** :
Fixes #492 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by IvySong2016** [comment]
the implement about how to append environment is ok, but there is no reference in the preprocessor for end user the specify the env pairs they want to set.

**Comment by jinchihe** [comment]
> the implement about how to append environment is ok, but there is no reference in the preprocessor for end user the specify the env pairs they want to set.

Thanks. The pod spec is generated in builder. So that's better to set env via `pod_spec_mutators`. For example:

```
from kubeflow.fairing.deployers.job import Job
from kubeflow.fairing.kubernetes import utils

Job(namespace=xxx, pod_spec_mutators=[utils.add_env({'var1': 'value1', 'var2', 'value2', ...})])
```

**Comment by fenglixa** [comment]
Thanks @jinchihe, 
/lgtm

**Comment by xauthulei** [comment]
/lgtm
Thanks @jinchihe

**Pull request merged**
