### PR TITLE
Work around presubmit tests timeout problems

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:
debug presubmit tests timeout problems.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/353)

### CODE REVIEW

**Comment by jinchihe** [comment]
Current found: If I commented below cases, the presubmit can be finished normally. Will do more to reduce scope.
```
test_job_submission_gkebackend_gcs_access_with_default_namespace
test_job_submission_gkebackend_gcs_access_with_kubeflow_namespace
test_xgboost_highlevel_apis
test_lightgbm
test_job_pvc_mounting_without_path
test_serving_pvc_mounting
test_serving_pvc_mounting_without_path
```

**Comment by jinchihe** [comment]
/assign @karthikv2k 
/assign @abhi-g 

After investigation, there are 2 cases that will cause presubmit hangs.
```
test_xgboost_highlevel_apis
test_lightgbm
```
I commented the `test_xgboost_highlevel_apis` and `test_lightgbm` by adding `pass_`, since the roor cuase is not clear now.

There are two cases will cause presubnmit running long time, since waiting for serving started, in fact the case just development attaching with pvc, no need service start, just updated service type to work around.
```
test_serving_pvc_mounting
test_serving_pvc_mounting_without_path
```

And I rollbacked the changes in #343 , that's OK now.

Could please take a look with high priority and let check-in so that avoiding block PR merging. Thanks.

**Comment by karthikv2k** [comment]
I found that the timeout issue was due to lack of garbage collection on  resources like load balancer that exceeded project quota . I cleared everything manually and tests pass as usual for now until we hit the limit again. Closing this PR as we don't need to comment out any tests.

**Comment by jinchihe** [comment]
@karthikv2k Got that, Thanks a lot!

**Comment by abhi-g** [comment]
Thanks for debugging Karthik! Similar to kf/kf we'd want these resources to be gced automatically if possible.

**Pull request closed without merging**
