### PR TITLE
Add Kubeflow Fairing E2E Sample

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:

The PR is going to:
- Add an Faring E2E sample. There are some examples, but that's part of ML, in fact Fairing supports E2E ML, such as building, training and deploying. The PR is going to add one E2E sample that using Fairing to build docker image and launch TFJob for distributed training, and then create a InferenceService (KFServing CRD) to deploy model service.

- Removed old kfserving example, that's duplicated with this one, and seems have problems.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/464)

### CODE REVIEW

**Comment by jinchihe** [comment]
/cc @abhi-g 

Could you please take a look? Thanks a lot!

**Comment by jinchihe** [comment]
/hold
Let the PR #466 merge firstly, then I will update to specify the deployers name. Thanks.

**Comment by jinchihe** [comment]
/hold cancel

@abhi-g This is ready for reviewing. Thanks a lot!

**Comment by abhi-g** [comment]
Awesome. Thanks @jinchihe.

Might be worth integrating kfserving into examples repo as well...

/lgtm
/approve

**Pull request merged**
