### PR TITLE
Feature/add streaming logging for aiplatform

### PR DESCRIPTION
**Pull request by pshiko**
**What this PR does / why we need it**:
Support streaming logs with GCP deployer that uses AI Platform

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

Thanks for your review!

When using fairing with GCP AI Platform, it was incovenient to not be able to get the job logs.
GCP does not have a streaming-capable client like the kubernetes client, but we can replicate it with a stackdriver client.
This is a slightly hack-like technique and may not be optimal, but the benefits are huge.
It would be great if you could check for any issues with the implementation!

Following is the result of running [example/gcp/hello-world-gpu-pytorch.py](https://github.com/kubeflow/fairing/blob/master/examples/gcp/hello-world-gpu-pytorch.py) using fairing with this pr.

スクリーンショット 2020-01-14 23 11 30

I also noticed a bug in the example, so I fixed it.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/444)

### CODE REVIEW

**Comment by abhi-g** [comment]
Hold the tests. There is an authorization issue going on that is blocking
and making the tests fail unrelated to your change

**Comment by pshiko** [comment]
@abhi-g  

Thank you !!
I was confused because only names of the failed test cases was displayed on the Argo UI and I could not check logs detail of failed task 😇 💣 
Would you notify me when the authentication problem is resolved?

**Comment by abhi-g** [comment]
yes, I am working on getting it resolved and will update.

**Comment by abhi-g** [comment]
/lgtm

waiting for @jinchihe to take a look as well.

**Comment by jinchihe** [comment]
@pshiko Thanks for the great contribution! 

/approve

**Pull request merged**
