### PR TITLE
#383 Use absolute paths

### LINKED ISSUE #383: Use absolute python imports
/kind feature

It looks like some of the code is using relative imports; e.g.
https://github.com/kubeflow/fairing/blob/master/kubeflow/fairing/builders/cluster/cluster.py#L6

We should probably clean that up and use absolute imports everywhere. In my experience using relative imports is brittle.

### PR DESCRIPTION
**Pull request by nrchakradhar**
**What this PR does / why we need it**:
Moving from relative import paths to explicti absolute paths
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #383 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
NONE
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/386)

### CODE REVIEW

**Comment by jinchihe** [comment]
@nrchakradhar do you address all relative imports under `kubeflow/fairing`?, since I think there are 100+ files, seems just update 31 files. Not sure, just confirm.

**Comment by nrchakradhar** [comment]
> @nrchakradhar do you address all relative imports under `kubeflow/fairing`?, since I think there are 100+ files, seems just update 31 files. Not sure, just confirm.

@jinchihe I ran the following command and got the output and hope it covers all relative imports.
-bash-4.2$ **grep -Rl "from \."**
kubeflow/fairing/__init__.py
kubeflow/fairing/backends/__init__.py
kubeflow/fairing/backends/backends.py
kubeflow/fairing/builders/append/append.py
kubeflow/fairing/builders/base_builder.py
kubeflow/fairing/builders/cluster/azurestorage_context.py
kubeflow/fairing/builders/cluster/cluster.py
kubeflow/fairing/builders/cluster/gcs_context.py
kubeflow/fairing/builders/cluster/s3_context.py
kubeflow/fairing/builders/docker/docker.py
kubeflow/fairing/builders/dockerfile.py
kubeflow/fairing/cloud/aws.py
kubeflow/fairing/cloud/azure.py
kubeflow/fairing/cloud/docker.py
kubeflow/fairing/cloud/gcp.py
kubeflow/fairing/config.py
kubeflow/fairing/deployers/gcp/gcp.py
kubeflow/fairing/deployers/gcp/gcpserving.py
kubeflow/fairing/deployers/job/job.py
kubeflow/fairing/deployers/kfserving/kfserving.py
kubeflow/fairing/deployers/serving/serving.py
kubeflow/fairing/deployers/tfjob/tfjob.py
kubeflow/fairing/frameworks/lightgbm.py
kubeflow/fairing/http_utils.py
kubeflow/fairing/kubernetes/manager.py
kubeflow/fairing/kubernetes/utils.py
kubeflow/fairing/ml_tasks/tasks.py
kubeflow/fairing/ml_tasks/utils.py
kubeflow/fairing/preprocessors/base.py
kubeflow/fairing/preprocessors/converted_notebook.py
kubeflow/fairing/preprocessors/full_notebook.py
kubeflow/fairing/preprocessors/function.py

Except the below files, I have modified all.
tests/integration/azure/test_running_in_notebooks.py
tests/integration/gcp/test_running_in_notebooks.py

**Comment by jlewi** [comment]
I'll let @jinchihe review this

**Comment by jinchihe** [comment]
@nrchakradhar seems one case failed due to import, could you please address this? Thanks.

```
Step #2: ==================================== ERRORS ====================================
Step #2: ______ ERROR collecting tests/integration/gcp/test_gcp_high_level_apis.py ______
Step #2: ImportError while importing test module '/workspace/tests/integration/gcp/test_gcp_high_level_apis.py'.
Step #2: Hint: make sure your test modules/packages have valid Python names.
Step #2: Traceback:
Step #2: tests/integration/gcp/test_gcp_high_level_apis.py:9: in <module>
Step #2:     from kubeflow.fairing.backends import KubeflowGKEBackend, GKEBackend, GCPManagedBackend
Step #2: E   ImportError: cannot import name 'KubeflowGKEBackend' from 'kubeflow.fairing.backends' (/workspace/kubeflow/fairing/backends/
__init__.py)
Step #2: =================================== FAILURES ===================================
Step #2: _______________________ test_xgboost_highlevel_apis_gke ________________________
```

**Comment by jinchihe** [comment]
@nrchakradhar Thanks for the quick action!
/lgtm
/approve

**Comment by nrchakradhar** [comment]
@jinchihe I guess the change in __init__.py fixed the import issue. Should this be done in other cases also where there is repetition of module name and file name. My search in google did not provide any convincing choices.

**Pull request merged**
