### PR TITLE
Work around k8s client issue to avoid blocking CI tests

### LINKED ISSUE #421: No module named 'kubernetes.client.api' in CI tests
Kubeflow fairing CI failed due to
```
../../kubeflow/fairing/builders/base_builder.py:3: in <module>
    from kubernetes import client
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/kubernetes-11.0.0b1-py3.7.egg/kubernetes/__init__.py:19: in <module>
    import kubernetes.client
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/kubernetes-11.0.0b1-py3.7.egg/kubernetes/client/__init__.py:20: in <module>
    from kubernetes.client.api.admissionregistration_api import AdmissionregistrationApi
E   ModuleNotFoundError: No module named 'kubernetes.client.api'
```

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:
Work around k8s client issue to avoid blocking CI tests
```
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/kubernetes-11.0.0b1-py3.7.egg/kubernetes/__init__.py:19: in <module>
    import kubernetes.client
/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/kubernetes-11.0.0b1-py3.7.egg/kubernetes/client/__init__.py:20: in <module>
    from kubernetes.client.api.admissionregistration_api import AdmissionregistrationApi
E   ModuleNotFoundError: No module named 'kubernetes.client.api'
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #421 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/422)

### CODE REVIEW

**Comment by consideRatio** [comment]
The current change is a robust fix, but also hard coding the fix for this version and for this PyPI package specifically. It is only needed to add the `<11` part in the requirements.txt file for when `python setup.py install` is used to install the requirements. If `pip install -r requirements.txt` instead is used directly, pip will not use the pre-release of unless you also add the `--pre` flag to the pip install command.

**Comment by jinchihe** [comment]
@consideRatio Great thanks for the comments, totally agree with you, we install Kubeflow fairing using `setup.py` in CI tests. This is a work around solution, and seems work fine. Once the problem in k8s Python client, we will remove the `<11.0.0`. But for now, we need to work around to avoid blocking CI test and PR merging. Thanks.

/test kubeflow-fairing-presubmit

**Comment by jinchihe** [comment]
Seems the CI tests caused by env problem?
```
tep #2: [gw0] [ 77%] PASSED tests/integration/common/test_full_notebook.py::test_full_notebook_job
Step #2: tests/integration/common/test_kubeflow_training.py::test_cluster_builder
Step #2: [gw0] [ 78%] PASSED tests/integration/common/test_kubeflow_training.py::test_cluster_builder
Step #2: tests/integration/gcp/test_gcs_access.py::test_job_submission_without_gcs_access
ERROR: (gcloud.builds.submit) [Errno 104] Connection reset by peer
```

**Pull request closed without merging**
