### PR TITLE
fix logical bug

### PR DESCRIPTION
**Pull request by xauthulei**
fixed issue #315 
@jinchihe ,Could you review this, thanks

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/420)

### CODE REVIEW

**Comment by jinchihe** [comment]
@xauthulei Thanks for the contribution. But I think if Workload Identity is enabled, may not user-gcp-sa credentials secret now? I'm not sure if still need to logical now, just remove the `if`? 

comments? @abhi-g

**Comment by abhi-g** [comment]
@jinchihe I think you are correct. We can remove that if condition completely. If there is no way to guess the correct builder, it's most likely not because of credentials.

**Comment by xauthulei** [comment]
@jinchihe and @abhi-g ,Thanks for your great review efforts .I have remove the `if` condition and related message.

**Pull request merged**
