### PR TITLE
Refresh the deploy service process.

### LINKED ISSUE #441: Prediction readme need to be refreshed
In the current prediction [Readme](https://github.com/kubeflow/fairing/blob/master/examples/prediction/README.md), the docker image creating process is not right:
```
[W 200109 15:38:03 docker:41] Docker command: ['python']
[I 200109 15:38:03 base:106] Creating docker context: /tmp/fairing_context_0oi3kpyk
[W 200109 15:38:03 docker:56] Building docker image docker.io/ibmlei/fairing-job:6A26E437...
[I 200109 15:38:03 docker:103] Build output: Step 1/6 : FROM seldonio/seldon-core-s2i-python3:0.4
[I 200109 15:38:03 docker:103] Build output: 
[I 200109 15:38:03 docker:103] Build output: ---> aaff5ae96530
[I 200109 15:38:03 docker:103] Build output: Step 2/6 : WORKDIR /app/
[I 200109 15:38:03 docker:103] Build output: 
[I 200109 15:38:03 docker:103] Build output: ---> Using cache
[I 200109 15:38:03 docker:103] Build output: ---> d4839c9ce130
[I 200109 15:38:03 docker:103] Build output: Step 3/6 : ENV FAIRING_RUNTIME 1
[I 200109 15:38:03 docker:103] Build output: 
[I 200109 15:38:03 docker:103] Build output: ---> Using cache
[I 200109 15:38:03 docker:103] Build output: ---> b41f3934fb88
[I 200109 15:38:03 docker:103] Build output: Step 4/6 : RUN if [ -e requirements.txt ];then pip install --no-cache -r requirements.txt; fi
[I 200109 15:38:03 docker:103] Build output: 
[I 200109 15:38:03 docker:103] Build output: ---> Using cache
[I 200109 15:38:03 docker:103] Build output: ---> 90f115c1b61d
[I 200109 15:38:03 docker:103] Build output: Step 5/6 : COPY /app/ /app/
[I 200109 15:38:03 docker:103] Build output: 
[I 200109 15:38:03 docker:103] Build output: ---> Using cache
[I 200109 15:38:03 docker:103] Build output: ---> 9a78383acc96
[I 200109 15:38:03 docker:103] Build output: Step 6/6 : CMD python
[I 200109 15:38:03 docker:103] Build output: 
[I 200109 15:38:03 docker:103] Build output: ---> Using cache
[I 200109 15:38:03 docker:103] Build output: ---> 18e4e41a1ad2
[I 200109 15:38:03 docker:103] Push finished: {'ID': 'sha256:18e4e41a1ad21c8edebb6c5a1f25aaf490aa1928a2083f9b91ee976d54d8c277'}
[I 200109 15:38:03 docker:103] Build output: Successfully built 18e4e41a1ad2
```
If you deploy it later, you will find the new images will not include the files: `HousingServe.py`,`requirements.txt`, `trained_ames_model.dat`
Also, the running env will miss the python libs recorded in `requirements.txt`

### PR DESCRIPTION
**Pull request by xauthulei**
Fixes #441 
/cc @jinchihe , please review this, Thanks

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/442)

### CODE REVIEW

**Comment by jinchihe** [comment]
Pls rebase also, thanks @xauthulei

**Comment by abhi-g** [comment]
@xauthulei please rebase this PR on upstream/master to pull in the test fixes. Since this PR only changes a readme, it should be easier to verify.

**Comment by xauthulei** [comment]
@abhi-g , Thanks , it is successful now.

**Comment by jinchihe** [comment]
/lgtm
/approve

Thanks @xauthulei

**Pull request merged**
