### PR TITLE
minio context source for vanilla k8s

### LINKED ISSUE #456: InCluster Builder - Context Source for vanilla-k8s
/kind feature

**Describe the solution you'd like**
Currently, there are two docker context sources for kaniko used for the in-cluster builder.
1. GCS
2. S3

For vanilla-k8s, it'd be good to add two options:
1. MinioContextSource
2. VolumeContextSource

**Anything else you would like to add:**
This is currently a blocker for https://github.com/kubeflow/examples/issues/725

/cc @johnugeorge @jlewi

### PR DESCRIPTION
**Pull request by swiftdiaries**
**What this PR does / why we need it**:
Adds a minio context source for the in-cluster builder.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #456 

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Adds a minio context source for in-cluster builder in vanilla k8s clusters.
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/458)

### CODE REVIEW

**Comment by abhi-g** [comment]
@swiftdiaries Thanks for the PR. Please fix the lint issues.

**Comment by abhi-g** [comment]
From the logs,
************* Module kubeflow.fairing.builders.cluster.minio_context
INFO|2020-02-13T07:20:07|util.py:72| C: 11, 0: Wrong continued indentation (add 1 space).
INFO|2020-02-13T07:20:07|util.py:72| endpoint_url,
INFO|2020-02-13T07:20:07|util.py:72| ^| (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 12, 0: Wrong continued indentation (add 1 space).
INFO|2020-02-13T07:20:07|util.py:72| minio_secret,
INFO|2020-02-13T07:20:07|util.py:72| ^| (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 13, 0: Wrong continued indentation (add 1 space).
INFO|2020-02-13T07:20:07|util.py:72| minio_secret_key,
INFO|2020-02-13T07:20:07|util.py:72| ^| (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 14, 0: Wrong continued indentation (add 1 space).
INFO|2020-02-13T07:20:07|util.py:72| region_name):
INFO|2020-02-13T07:20:07|util.py:72| ^| (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 20, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:07|util.py:72| C: 27, 0: Wrong continued indentation (add 5 spaces).
INFO|2020-02-13T07:20:07|util.py:72| self.minio_secret,
INFO|2020-02-13T07:20:07|util.py:72| ^    | (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 28, 0: Wrong continued indentation (add 5 spaces).
INFO|2020-02-13T07:20:07|util.py:72| self.minio_secret_key,
INFO|2020-02-13T07:20:07|util.py:72| ^    | (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 29, 0: Wrong continued indentation (add 5 spaces).
INFO|2020-02-13T07:20:07|util.py:72| self.region_name)
INFO|2020-02-13T07:20:07|util.py:72| ^    | (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 33, 0: Wrong continued indentation (add 1 space).
INFO|2020-02-13T07:20:07|util.py:72| bucket_name=bucket_name,
INFO|2020-02-13T07:20:07|util.py:72| ^| (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 34, 0: Wrong continued indentation (add 1 space).
INFO|2020-02-13T07:20:07|util.py:72| file_to_upload=context_filename)
INFO|2020-02-13T07:20:07|util.py:72| ^| (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 48, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:07|util.py:72| C: 48, 0: Line too long (107/100) (line-too-long)
INFO|2020-02-13T07:20:07|util.py:72| C: 49, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:07|util.py:72| C: 49, 0: Line too long (115/100) (line-too-long)
INFO|2020-02-13T07:20:07|util.py:72| C: 50, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:07|util.py:72| C: 50, 0: Line too long (123/100) (line-too-long)
INFO|2020-02-13T07:20:07|util.py:72| C: 51, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:07|util.py:72| C: 51, 0: Line too long (109/100) (line-too-long)
INFO|2020-02-13T07:20:07|util.py:72| C: 52, 0: Line too long (107/100) (line-too-long)
INFO|2020-02-13T07:20:07|util.py:72| C: 54, 0: Wrong continued indentation (add 2 spaces).
INFO|2020-02-13T07:20:07|util.py:72| mount_path="/kaniko/.docker/")],
INFO|2020-02-13T07:20:07|util.py:72| ^ | (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 54, 0: Line too long (109/100) (line-too-long)
INFO|2020-02-13T07:20:07|util.py:72| C: 56, 0: Wrong hanging indentation (remove 28 spaces).
INFO|2020-02-13T07:20:07|util.py:72| restart_policy='Never',
INFO|2020-02-13T07:20:07|util.py:72| |                           ^ (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 57, 0: Wrong hanging indentation (remove 28 spaces).
INFO|2020-02-13T07:20:07|util.py:72| volumes=[client.V1Volume(name="docker-config",
INFO|2020-02-13T07:20:07|util.py:72| |                           ^ (bad-continuation)
INFO|2020-02-13T07:20:07|util.py:72| C: 57, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:07|util.py:72| C: 58, 0: Line too long (131/100) (line-too-long)
INFO|2020-02-13T07:20:07|util.py:72| W: 21, 4: Parameters differ from overridden 'prepare' method (arguments-differ)
INFO|2020-02-13T07:20:07|util.py:72| W: 35, 4: Parameters differ from overridden 'generate_pod_spec' method (arguments-differ)
INFO|2020-02-13T07:20:07|util.py:72| 
INFO|2020-02-13T07:20:07|util.py:72| -----------------------------------
INFO|2020-02-13T07:20:07|util.py:72| Your code has been rated at 0.36/10

And,
INFO|2020-02-13T07:20:27|util.py:72| ************* Module kubeflow.fairing.cloud.k8s
INFO|2020-02-13T07:20:27|util.py:72| C:  7, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:27|util.py:72| C:  8, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:27|util.py:72| C:  9, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:27|util.py:72| C: 10, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:27|util.py:72| C: 14, 0: Wrong continued indentation (add 16 spaces).
INFO|2020-02-13T07:20:27|util.py:72| endpoint_url=endpoint_url,
INFO|2020-02-13T07:20:27|util.py:72| ^               | (bad-continuation)
INFO|2020-02-13T07:20:27|util.py:72| C: 15, 0: Wrong continued indentation (add 16 spaces).
INFO|2020-02-13T07:20:27|util.py:72| aws_access_key_id=minio_secret,
INFO|2020-02-13T07:20:27|util.py:72| ^               | (bad-continuation)
INFO|2020-02-13T07:20:27|util.py:72| C: 16, 0: Wrong continued indentation (add 16 spaces).
INFO|2020-02-13T07:20:27|util.py:72| aws_secret_access_key=minio_secret_key,
INFO|2020-02-13T07:20:27|util.py:72| ^               | (bad-continuation)
INFO|2020-02-13T07:20:27|util.py:72| C: 17, 0: Wrong continued indentation (add 16 spaces).
INFO|2020-02-13T07:20:27|util.py:72| config=Config(signature_version='s3v4'),
INFO|2020-02-13T07:20:27|util.py:72| ^               | (bad-continuation)
INFO|2020-02-13T07:20:27|util.py:72| C: 18, 0: Wrong continued indentation (add 16 spaces).
INFO|2020-02-13T07:20:27|util.py:72| region_name=region_name,
INFO|2020-02-13T07:20:27|util.py:72| ^               | (bad-continuation)
INFO|2020-02-13T07:20:27|util.py:72| C: 19, 0: Wrong continued indentation (add 16 spaces).
INFO|2020-02-13T07:20:27|util.py:72| use_ssl=False)
INFO|2020-02-13T07:20:27|util.py:72| ^               | (bad-continuation)
INFO|2020-02-13T07:20:27|util.py:72| C: 26, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:27|util.py:72| C: 27, 0: Trailing whitespace (trailing-whitespace)
INFO|2020-02-13T07:20:27|util.py:72| C: 28, 0: Wrong continued indentation (add 4 spaces).
INFO|2020-02-13T07:20:27|util.py:72| blob_name,
INFO|2020-02-13T07:20:27|util.py:72| ^   | (bad-continuation)
INFO|2020-02-13T07:20:27|util.py:72| C: 29, 0: Wrong continued indentation (add 4 spaces).
INFO|2020-02-13T07:20:27|util.py:72| bucket_name,
INFO|2020-02-13T07:20:27|util.py:72| ^   | (bad-continuation)
INFO|2020-02-13T07:20:27|util.py:72| C: 30, 0: Wrong continued indentation (add 4 spaces).
INFO|2020-02-13T07:20:27|util.py:72| file_to_upload):
INFO|2020-02-13T07:20:27|util.py:72| ^   | (bad-continuation)
INFO|2020-02-13T07:20:27|util.py:72| W:  4, 0: Unused utils imported from kubeflow.fairing (unused-import)
INFO|2020-02-13T07:20:27|util.py:72|

**Comment by swiftdiaries** [comment]
Thanks for the quick merge !

**Pull request merged**
