### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by r2d4**
This is a pretty large refactor so let me describe some of what is going on:

* Stages were made a bit more explicit - they are preprocess, build, and deploy.
* Decorators are gone and replaced with a config builder approach
* The fairing runtime dependency is removed, so any base image can be used

### preprocess 
takes a set of inputs and translate them to a context for the builder.

**base_preprocessor** - adds the fairing runtime files and all of the files in the directory. Defaults to a python entrypoint and command.

**full_notebook_preprocessor** - schedules an entire notebook for execution

**converted_notebook_preprocessor** - converts a notebook to a python file prepares a context for that

### build
build is relatively unchanged, except many of the duplicate code has been centralized in the base_builder class

* Knative dependency is removed - we now invoke the in-cluster builder directly instead of going through a knative template and CRD. In the future I'd like to support multiple context sources like skaffold - but for now it only supports the upload-to-gcs flow.

### deploy
deploy also is relatively unchanged, and there is probably more code de-duping to do

## Config
The config is moved away from decorators, and uses a string to class map to avoid imports directly in the user's file. There have been some minor renamings in the cross over from decorator to config.

## No runtime dependency on fairing

This is accomplished by adding a runtime_config shim file that passes through to the model's train function. We automatically add this to the context, and any base image can be used.

TODO
- [ ] Update documentation
- [ ] Add some tests

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/64)

### CODE REVIEW

**Comment by r2d4** [comment]
Fixes #47 
Fixes #42

**Comment by jlewi** [comment]
/lgtm
/hold

@r2d4 None of my changes are blocking. I think the main comment I have is to sync up with @karthikv2k and make sure he's on board with the syntax and other user facing design choices. You can do that either before or after this PR is merge.d

**Comment by karthikv2k** [comment]
We are meeting today to talk about syntax and other design choices and get an alignment.

**Pull request merged**
