### PR TITLE
Fix bug for V1alpha2TensorRTSpec ImportError

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:
Fix bug for V1alpha2TensorRTSpec ImportError
```
 from kfserving import V1alpha2TensorRTSpec
ImportError: cannot import name 'V1alpha2TensorRTSpec'
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubeflow/examples/issues/806

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by jinchihe** [comment]
Seems the new `cloudpickle` has some problem, we pined to old one. Thanks

**Comment by xauthulei** [comment]
/lgtm
Thanks @jinchihe

**Pull request merged**
