### PR TITLE
apply pylint testing

### LINKED ISSUE #298: Suggest adding pylint tests in kubeflow-fairing-presubmit for Fairing
/kind feature

**Describe the solution you'd like**
Since this is Python project, suggest adding `pylint` tests in `kubeflow-fairing-presubmit`. `pylint` is very useful tool to check errors in Python code, and can ensure code standard.

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:
Apply pylint testing for the kubeflow fairing since this is python project and pylint is very useful tool for python code standardization.

**Which issue(s) this PR fixes**:
Fixes #298 #82 

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/300)

### CODE REVIEW

**Comment by jinchihe** [comment]
From the testing, there are so many lint errors. We need to big effort to fix this.  :-(
```
ERROR|2019-06-24T13:55:09|test_py_lint.py:76| 111 files had lint errors:
```

/cc @karthikv2k

**Comment by jinchihe** [comment]
/assign @karthikv2k @abhi-g 

I fixed some pylint errors, and disabled some ones. Could you please help to review? As you can see, the code changes are huge, but I think the risk is lower. we should invole pylint tests for python porject at the begining, but it's not late :-) The presubmit passed now.  Thanks a lot!

**Comment by jinchihe** [comment]
kindly ping @karthikv2k @abhi-g Any comments for the pylint testing.
I suggest merging this as ealier as possiable to ensure following PR python code without pylint errors. Thanks.

**Comment by abhi-g** [comment]
Thanks @jinchihe for the cleanup across the code base and really sorry for the delay in the review. This is looking good. you'll probably need to merge from master and update a few more places..

/lgtm

**Comment by jinchihe** [comment]
@abhi-g OK, I will resove the confilcts once get chance. Thanks.

**Comment by abhi-g** [comment]
/test kubeflow-fairing-presubmit
trying to understand why is the  test taking so long. This used to be ~15-20min.

**Comment by jinchihe** [comment]
> /test kubeflow-fairing-presubmit
> trying to understand why is the test taking so long. This used to be ~15-20min.

I guess that's caused by test env problem, I noticed some problems in another PR, but just going to confirm the reasons, thanks.

**Comment by jinchihe** [comment]
@abhi-g Could you please take a look again? Thanks a lot!
I resolved all conficts. Once have any check-in files, need to take big effort to resolve conficts and handle the new files and code pylint problem :-) After the PR, the code owner should ensure that.

**Pull request merged**
