### PR TITLE
Add the code comment

### PR DESCRIPTION
**Pull request by xauthulei**
To address the issue #326 , Thanks

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/389)

### CODE REVIEW

**Comment by jinchihe** [comment]
wow! Great thanks @xauthulei , Will review later.

**Comment by jinchihe** [comment]
@xauthulei Could you please fix pylint failed cases? Thanks.

**Comment by xauthulei** [comment]
> @xauthulei Could you please fix pylint failed cases? Thanks.

@jinchihe , The errors have been fixed, please review that again. Thanks

**Pull request merged**
