### PR TITLE
Installing requirements earlier and fixing issues with cluster builder

### LINKED ISSUE #154: cluster builder is not passing namespace to context source and pod
This is resulting in not able to create secrets in default namespace.

### PR DESCRIPTION
**Pull request by karthikv2k**
Fixes #154 #152 
/hold
Waiting for #144 to write tests for this PR

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/155)

### CODE REVIEW

**Comment by karthikv2k** [comment]
CC  @zabbasi

**Comment by karthikv2k** [comment]
/hold cancel
Sorry I should really force push next time to avoid getting prev commits in master here. Also somehow I got duplicate commits too :(

The only two commits that needs review are: 
https://github.com/kubeflow/fairing/pull/155/commits/a093f4c39d2b929c869bf8c95951eddc10d8fa3a
https://github.com/kubeflow/fairing/pull/155/commits/64fb3ea30b9af31ab55ca511bff63cfc2afc10dc

**Comment by r2d4** [comment]
You should rebase the PR

**Comment by karthikv2k** [comment]
rebasing is creating more duplicate commits. Let me create fresh PR.

**Pull request closed without merging**
