### PR TITLE
add member comments to some methods

### PR DESCRIPTION
**Pull request by wzhanw**
add comments to some methods, made code easy to read.

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/396)

### CODE REVIEW

**Comment by jinchihe** [comment]
@wzhanw Could you please run pyment to generate docString format and then add some comments for this (as mentioned in #326 )? we need to have a uniform format to generate Fairing API doc in #338 

1. Please install [pyment](https://github.com/dadadel/pyment) and then use the tool to generate the docstring framework for your parts, 
2. And then add docStrings for each function and class manually, please see the PR https://github.com/kubeflow/fairing/pull/346 for examples.

**Comment by abhi-g** [comment]
Additionally, class docstrings should be placed after the class definition line. for eg.

class xyz(abc):
     """ Xyz is a fantastic way to do...
     """

**Comment by wzhanw** [comment]
@jinchihe I followed your instructions to correct the comments, please review again.

**Comment by jinchihe** [comment]
@wzhanw Great thanks!
/ok-to-test

**Comment by jinchihe** [comment]
Hello @wzhanw 

Seems there are some pylint problems with the changes, that's strange the there are 12 file failed, I guess that's caused by pylint script updated.

```
ERROR|2019-10-21T02:05:27|test_py_lint.py:88| 12 files had lint errors:
/build/lib/kubeflow/fairing/builders/append/append.py
/build/lib/kubeflow/fairing/builders/base_builder.py
/build/lib/kubeflow/fairing/builders/builder.py
/build/lib/kubeflow/fairing/builders/cluster/context_source.py
/build/lib/kubeflow/fairing/builders/docker/docker.py
/build/lib/kubeflow/fairing/builders/dockerfile.py
/kubeflow/fairing/builders/append/append.py
/kubeflow/fairing/builders/base_builder.py
/kubeflow/fairing/builders/builder.py
/kubeflow/fairing/builders/cluster/context_source.py
/kubeflow/fairing/builders/docker/docker.py
/kubeflow/fairing/builders/dockerfile.py
```

Feel free to get my help if you need for that. Thanks.

**Comment by abhi-g** [comment]
I looked through some of the pylint errors. They look valid errors. Please resolve. for eg;
/build/lib/kubeflow/fairing/builders/append/append.py
Using config file /mnt/test-data-volume/kubeflow-fairing-presubmit-e2e-396-0d1f5d0-6624-1083/src/kubeflow/fairing/.pylintrc
INFO|2019-10-21T01:58:48|util.py:69| ************* Module kubeflow.fairing.builders.append.append
INFO|2019-10-21T01:58:48|util.py:69| **C: 24, 0: Line too long (102/100) (line-too-long)**
INFO|2019-10-21T01:58:48|util.py:69| **C: 89, 0: Trailing whitespace (trailing-whitespace)**

Sorry its a bit painful, bit if you scroll through the log of the Junit test failure, you should be able to find all errors reported.

**Comment by wzhanw** [comment]
@abhi-g, @jinchihe  I fixed the pylint error, please review again.

**Comment by abhi-g** [comment]
@wzhanw Can you please merge master to ensure that fixes for tests to work with 0.7 are in there. That could be causing the current failure.

**Comment by jinchihe** [comment]
@wzhanw Great thanks! 
/lgtm
/approve

**Pull request merged**
