### PR TITLE
Support deploying pytorchjob using Kubeflow Fairing

### PR DESCRIPTION
**Pull request by jinchihe**
**What this PR does / why we need it**:
Support deploying pytorchjob using Kubeflow Fairing

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

1. Please confirm that if this PR changes any image versions, then that's the sole change this PR makes.

**Release note**:

```release-note
Support deploying pytorchjob using Kubeflow Fairing
```

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/fairing/436)

### CODE REVIEW

**Comment by jinchihe** [comment]
/assign @abhi-g 
Could you please take a look? Thanks!

**Comment by abhi-g** [comment]
Thanks @jinchihe.
/lgtm
/approve

**Pull request merged**
